### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by ZackAlfakir**
This should allow compiling from terminal, and will also create a static library located in ./.build/lib612.a

### CODE REVIEW

**Comment by ZackAlfakir** [comment]
Wait for the TravisCI check to complete before merging

**Comment by ZackAlfakir** [comment]
So, it compiles on my machine, but not on Travis (if you look at the log, it didn't actually compile) I will continue looking into it

**Comment by ZackAlfakir** [comment]
`[ 33%] Building CXX object CMakeFiles/FRCProgram.dir/src/roboRIO/AlignDrivetrain.cpp.o
/usr/bin/arm-frc-linux-gnueabi-g++    -Wno-unused-parameter -pedantic -fPIC -std=c++1y -I/home/travis/build/Chantilly612Code/NightOwl/wpilib/include -I/home/travis/build/Chantilly612Code/NightOwl/roboRIO -c -O0 -g3 -Wall -fmessage-length=0 -g   -o CMakeFiles/FRCProgram.dir/src/roboRIO/AlignDrivetrain.cpp.o -c /home/travis/build/Chantilly612Code/NightOwl/src/roboRIO/AlignDrivetrain.cpp
In file included from /home/travis/build/Chantilly612Code/NightOwl/src/roboRIO/AlignDrivetrain.cpp:1:0:
/home/travis/build/Chantilly612Code/NightOwl/src/roboRIO/AlignDrivetrain.h:4:35: fatal error: Commands/PIDSubsystem.h: No such file or directory
 #include "Commands/PIDSubsystem.h"
                                   ^
compilation terminated.
make[2]: *** [CMakeFiles/FRCProgram.dir/src/roboRIO/AlignDrivetrain.cpp.o] Error 1`

I'm guessing that PIDSubsystem is either something you guys have but did not include in the project, or something in a newer version of wpilib

**Comment by WardBenjamin** [comment]
My guess is that's it in a newer version of WPILib, since we've been using it all year. I'll look into this a bit.

**Comment by WardBenjamin** [comment]
Oh, lol. Nice to see that we don't need WPILib anymore :P

**Comment by ZackAlfakir** [comment]
@WardBenjamin : I realized that I commented out the part that runs the wpi downloader, making it not able to compile because it didnt have wpilib at all. Note that for some reason, the script runs every time no matter if I already have the library

**Comment by ZackAlfakir** [comment]
Looks like it's working now!

**Comment by WardBenjamin** [comment]
@ZackAlfakir PR looks good now; thanks. I also have that issue, I'll have to try to figure that out eventually. I think this should work, though. Merging!

**Comment by ZackAlfakir** [comment]
@WardBenjamin @Ahmad-Bamba , feel free to look over it and merge

**Comment by WardBenjamin** [comment]
I'm not going to delete the Travis branch yet because I want to change the output binary name tonight, since we're going to have other code called Lib612.

**Comment by ZackAlfakir** [comment]
@WardBenjamin just change the name that it is given in build.sh

**Comment by Ahmad-Bamba** [comment]
Thanks Zack!

**Pull request merged**
